
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Evento', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('codigo', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Evento')),('classe', models.CharField(db_index=True, max_length=2)),('tipo_utilizacao', models.CharField(db_index=True, max_length=1)),('sequencial', models.CharField(db_index=True, max_length=3)),('estorno', models.CharField(blank=True, max_length=1)),('especificacao', models.TextField(blank=True)),('fonte', models.CharField(default='Tabela de Eventos SIAFI 2025', max_length=100))], options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos', 'ordering': ['codigo']}),
        migrations.CreateModel(name='Situacao', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('codigo', models.CharField(db_index=True, max_length=10, unique=True)),('titulo', models.CharField(max_length=255)),('descricao', models.TextField(blank=True)),('tipo_documento_habil', models.CharField(blank=True, help_text='Ex.: PA, NP, FL etc.', max_length=20)),('origem', models.CharField(blank=True, max_length=255)),('observacao', models.TextField(blank=True))], options={'verbose_name': 'Situação', 'verbose_name_plural': 'Situações', 'ordering': ['codigo']}),
        migrations.CreateModel(name='LancamentoConta', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('uge', models.CharField(choices=[('UGE1', 'UGE 1'), ('UGE2', 'UGE 2')], max_length=4)),('natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),('conta', models.CharField(db_index=True, max_length=30)),('ordem', models.PositiveIntegerField(default=0)),('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='eventos.evento'))], options={'ordering': ['evento__codigo', 'ordem', 'uge', 'natureza']}),
        migrations.CreateModel(name='SituacaoEvento', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('tipo_evento', models.CharField(blank=True, help_text='Tipo de Evento parametrizado no CONSIT, quando conhecido.', max_length=50)),('confianca', models.CharField(choices=[('oficial', 'Oficial/CONSIT'), ('inferida', 'Inferida por contas e descrição'), ('manual', 'Manual do usuário')], default='inferida', max_length=20)),('justificativa', models.TextField(blank=True)),('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes_relacionadas', to='eventos.evento')),('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_relacionados', to='eventos.situacao'))], options={'verbose_name': 'Associação Situação x Evento', 'verbose_name_plural': 'Associações Situação x Evento', 'unique_together': {('situacao', 'evento', 'tipo_evento')}}),
        migrations.AddIndex(model_name='lancamentoconta', index=models.Index(fields=['conta'], name='eventos_lan_conta_5cdd11_idx')),
    ]
