# Generated by Django 5.2.14 on 2026-05-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lancamentoconta',
            new_name='eventos_lan_conta_8ff309_idx',
            old_name='eventos_lan_conta_5cdd11_idx',
        ),
    ]
